abacus:
  executable: "abacus"
  run_mode: "mpirun"
  np: 8
  pseudo_dir: "/home/yukino/TritonDFT-43C7/abacus_data/Pseudopotential"
  orb_dir: "/home/yukino/TritonDFT-43C7/abacus_data/StandardOrbitals"

decoder:
  mode: "llm"
  model: "deepseek-reasoner"
  base_url: "https://api.deepseek.com"
  api_key: "sk-b3065b9ae4854917ae56cb080553f60b"
  temperature: 0.0
  timeout: 5

MP_API_KEY: "vHFbY1EFbEj0IMvXeI6tyFnc5OY34nMN"
